log_dir: test_log_dir/run_0
run_num: 0
scenario: test
seed: 0
task_params:
  T: 300
  Tend: 3
  Ts: 0.01
  init_cond:
  - - -60
    - -20
    - 0
    - 0.3
    - -0.1
    - 0.6
    - -0.2
  - - -60
    - -20
    - 0
    - 0.7
    - 0.0
    - 0.6
    - -0.2
  - - 60
    - 20
    - 0
    - 0.7
    - 0.0
    - 0.6
    - 0.2
  iterations: 20
  learning_algorithm: MDREPS
  ntargets: 2
  num_samples: 6
  obs_like_mjc: false
  rdn_tgt_pos: true
  render: true
  sample_on_policy: false
  test_after_iter: true
  test_cond:
  - 0
  - 1
  test_n_samples: 2
  tf_iterations: 2000
  tgt_positions:
  - - 0.1
    - 0.2
  - - -0.1
    - -0.2
  tgt_weights:
  - 1.0
  - -1.0
  train_cond:
  - 0
  - 1
  use_global_policy: true
