<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

       <xacro:property name="x_positive" value="0.097" />
	<xacro:property name="x_negative" value="-0.081" />
       <xacro:property name="z_offset" value="-0.132" />
       <xacro:property name="ball_radius" value="0.02" />

       <xacro:macro name="reference_frame_forearm" params="parent name x z">
		<link name="${name}_link"/>

		<joint name="${name}_joint" type="fixed">
			<origin xyz="${x} 0 ${z}" rpy="0 0 0" />
			<parent link="${parent}"/>
			<child link="${name}_link"/>
		</joint>
	</xacro:macro>

       <xacro:macro name="references_frame_forearm" params="parent name">
		<xacro:reference_frame_forearm parent="${parent}" name="${name}_forward_contact" x="${x_positive}" z="${z_offset}" />
		<xacro:reference_frame_forearm parent="${parent}" name="${name}_backward_contact" x="${x_negative}" z="${z_offset}"/>	
              <xacro:reference_frame_forearm parent="${parent}" name="${name}_central_contact" x="0.0" z="${z_offset-ball_radius}"/>
	</xacro:macro>

       <xacro:references_frame_forearm parent="LRaisingSupport" name="l_forearm"/>
	<xacro:references_frame_forearm parent="RRaisingSupport" name="r_forearm"/>


</robot>
