<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<!-- ************** CHANGE BY USER ************** -->
<xacro:property name="EXTRA_MASS" value ="20.0" />
<xacro:property name="CYLINDER_RADIUS" value ="0.14" />
<xacro:property name="CYLINDER_HEIGHT" value ="0.15" />
<xacro:property name="WEIGHT_POSITION" value="0.1"/>
<!-- ******************************************** -->

<xacro:property name="mmTom" value="0.001" />
<xacro:property name="mm2Tom2" value="${0.001*0.001}" />
<xacro:property name="tonsToKg" value="1000.0" />

<xacro:property name="PI" value="3.14159265359" />
<xacro:property name="PI_2" value="1.57079632679" />

<xacro:property name="l" value="0.215"/>

<link name ="PelvisWeightBench">
    <inertial>
      <origin xyz="0.0 0.0 ${1.8846109e+02*mmTom}" rpy="0 0 0"/>
      <mass value="5.5278386"/>
      <inertia ixx="${1.5195067e+05*mm2Tom2}"  ixy="0.0"  ixz="${-2.4191890e-01*mm2Tom2}" iyy="${1.5213465e+05*mm2Tom2}" iyz="0.0" izz="${5.1389419e+03*mm2Tom2}" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry name="PelvisWeightBench_visual">
        <mesh filename="meshes/PelvisWeightBench.STL" scale="0.001 0.001 0.001" />
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry name="PelvisWeightBench_collision">
        <mesh filename="meshes/simple/PelvisWeightBench.STL" scale="0.001 0.001 0.001" />
      </geometry>             
    </collision>
</link>

<link name ="ExtraWeight">
    <inertial>
      <origin xyz="0.0 0.0 ${CYLINDER_HEIGHT/2.0}" rpy="0 0 0"/>
      <mass value="${EXTRA_MASS}"/>
      <inertia ixx="${EXTRA_MASS*CYLINDER_HEIGHT*CYLINDER_HEIGHT/12.0+EXTRA_MASS*CYLINDER_RADIUS*CYLINDER_RADIUS/4.0}"  ixy="0.0"  ixz="0.0" iyy="${EXTRA_MASS*CYLINDER_HEIGHT*CYLINDER_HEIGHT/12.0+EXTRA_MASS*CYLINDER_RADIUS*CYLINDER_RADIUS/4.0}" iyz="0.0" izz="${EXTRA_MASS*CYLINDER_RADIUS*CYLINDER_RADIUS/2.0}" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry name="ExtraWeight_visual">
        <cylinder length="${CYLINDER_HEIGHT}" radius="${CYLINDER_RADIUS}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry name="ExtraWeight_collision">
        <cylinder length="${CYLINDER_HEIGHT}" radius="${CYLINDER_RADIUS}"/>
      </geometry>             
    </collision>
</link>

<joint name="PelvisWeightBench_joint" type="fixed">
    <parent link="Waist"/>
    <child link="PelvisWeightBench"/>
    <origin xyz="-0.035 0 0.075" rpy="0 0 ${PI_2}" />
</joint>

<joint name="ExtraWeight_joint" type="fixed">
    <parent link="PelvisWeightBench"/>
    <child link="ExtraWeight"/>
    <origin xyz="0.0 0 ${l+CYLINDER_HEIGHT/2.0+WEIGHT_POSITION}" rpy="0 0 0" />
</joint>  

</robot>
