<?xml version="1.0"?>
<!-- Manipulator 2D robot (based on Revolute-Revolute Manipulator) -->
<robot name="manipulator2d" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_z" value="0.0" /> <!-- Height from world to base_link -->
  <xacro:property name="radius_base" value="0.01" />
  <xacro:property name="inner_radius_base" value="0.008" />
  <xacro:property name="joints_radius" value="0.025" />
  <xacro:property name="joints_inner_radius" value="0.0245" />
  <xacro:property name="height_base" value="0.10" /> <!-- Base -->
  <xacro:property name="height1" value="0.3" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.2" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.1" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="camera_x" value="0.0" /> <!-- X position 'camera' -->
  <xacro:property name="camera_y" value="0.0" /> <!-- Y position 'camera' -->
  <xacro:property name="camera_z" value="1.2" /> <!-- Z position 'camera' -->
  <xacro:property name="axel_offset" value="${joints_radius + 0.01}" />
  <xacro:property name="radius_axel" value="${axel_offset + 0.01}" />
  <xacro:property name="height_axel" value="${joints_radius*2}" />
  <xacro:property name="md_base" value="7850" /> <!-- Mass density -->
  <xacro:property name="md_links" value="2700" />
  <xacro:property name="mass_base" value="${md_base*PI*(radius_base-inner_radius_base)*height_base}" />
  <xacro:property name="mass1" value="${md_links*PI*(joints_radius-joints_inner_radius)*height1}" />
  <xacro:property name="mass2" value="${md_links*PI*(joints_radius-joints_inner_radius)*height2}" />
  <xacro:property name="mass3" value="${md_links*PI*(joints_radius-joints_inner_radius)*height3}" />
  <xacro:property name="yt" value="0.14" /> <!-- Internal gripper width -->
  <xacro:property name="y1" value="0.02" />
  <xacro:property name="zt" value="0.10" /> <!-- Internal gripper length -->
  <xacro:property name="z1" value="0.015" />
  <xacro:property name="xt" value="0.025" />
  <xacro:property name="gripper_mass" value="0.1" />
  <xacro:property name="dummy_mass" value="0.001" />
  <xacro:property name="dummy_inertia" value="0.001" />

  <!--&lt;!&ndash; Import all Gazebo-customization elements, including Gazebo colors &ndash;&gt;-->
  <!--<xacro:include filename="$(find manipulator2d_description)/urdf/manipulator2d.gazebo" />-->
  <!--&lt;!&ndash; Import Rviz colors &ndash;&gt;-->
  <!--<xacro:include filename="$(find manipulator2d_description)/urdf/materials.xacro" />-->

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <!--<joint name="fixed" type="fixed">-->
    <!--<parent link="world"/>-->
    <!--<child link="link1"/>-->
    <!--<origin xyz="0 0 ${base_z}" rpy="0 0 0"/>-->
  <!--</joint>-->

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_z}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <collision>
      <origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${height_base}" radius="${radius_base}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${height_base}" radius="${radius_base}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
      <mass value="${mass_base}"/>
      <inertia
      ixx="${mass_base / 12.0 * (3*radius_base*radius_base + height_base*height_base)}" ixy="0.0" ixz="0.0"
      iyy="${mass_base / 12.0 * (3*radius_base*radius_base + height_base*height_base)}" iyz="0.0"
      izz="${mass_base / 2.0 * (radius_base*radius_base)}"/>
    </inertial>
  </link>

  <joint name="joint0" type="revolute">
      <parent link="base_link"/>
      <child link="coupler0"/>
      <origin xyz="0 0 ${height_base/2+joints_radius}" rpy="0 0 0"/>
      <limit effort="100.0" lower="-2.18" upper="2.18" velocity="0.5"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.7"/>
  </joint>

  <link name="coupler0">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <!--<sphere radius="${radius_axel}"/>-->
        <cylinder length="${height_axel}" radius="${radius_axel}"/>
      </geometry>
      <material name="white"/>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <!--<sphere radius="${radius_axel}"/>-->
        <cylinder length="${height_axel}" radius="${radius_axel}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${dummy_mass}"/>
      <inertia
          ixx="${dummy_inertia}" ixy="0.0" ixz="0.0"
          iyy="${dummy_inertia}" iyz="0.0"
          izz="${dummy_inertia}"/>
    </inertial>
  </link>

  <joint name="coupler_joint0" type="fixed">
    <parent link="coupler0"/>
    <child link="link1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="${height1/2} 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${height1}" radius="${joints_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${height1/2} 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${height1}" radius="${joints_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="${height1/2} 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <mass value="${mass1}"/>
      <inertia
      ixx="${mass1 / 12.0 * (3*joints_radius*joints_radius + height1*height1)}" ixy="0.0" ixz="0.0"
      iyy="${mass1 / 12.0 * (3*joints_radius*joints_radius + height1*height1)}" iyz="0.0"
      izz="${mass1 / 2.0 * (joints_radius*joints_radius)}"/>
    </inertial>

  </link>

  <!--<joint name="joint1" type="revolute">-->
    <!--<parent link="link1"/>-->
    <!--<child link="link2"/>-->
    <!--<origin xyz="${height1 + axel_offset} 0 0" rpy="0 0 0"/>-->
    <!--<limit effort="100.0" lower="-2.18" upper="2.18" velocity="0.5"/>-->
    <!--<axis xyz="0 0 1"/>-->
    <!--<dynamics damping="0.7"/>-->
  <!--</joint>-->

  <joint name="joint1" type="revolute">
    <parent link="link1"/>
    <child link="coupler1"/>
    <origin xyz="${height1 + axel_offset} 0 0" rpy="0 0 0"/>
    <limit effort="100.0" lower="-2.18" upper="2.18" velocity="0.5"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="coupler1">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${height_axel}" radius="${radius_axel}"/>
      </geometry>
      <material name="white"/>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${height_axel}" radius="${radius_axel}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${dummy_mass}"/>
      <inertia
          ixx="${dummy_inertia}" ixy="0.0" ixz="0.0"
          iyy="${dummy_inertia}" iyz="0.0"
          izz="${dummy_inertia}"/>
    </inertial>
  </link>

  <joint name="coupler_joint1" type="fixed">
    <parent link="coupler1"/>
    <child link="link2"/>
    <origin xyz="${axel_offset} 0 0" rpy="0 0 0"/>
  </joint>

   <!--Middle Link-->
  <link name="link2">
    <collision>
      <origin xyz="${height2/2} 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${height2}" radius="${joints_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${height2/2} 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${height2}" radius="${joints_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="${height2/2} 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <mass value="${mass2}"/>
      <inertia
      ixx="${mass2 / 12.0 * (3*joints_radius*joints_radius + height1*height2)}" ixy="0.0" ixz="0.0"
      iyy="${mass2 / 12.0 * (3*joints_radius*joints_radius + height1*height2)}" iyz="0.0"
      izz="${mass2 / 2.0 * (joints_radius*joints_radius)}"/>
    </inertial>
  </link>

  <!--<joint name="joint2" type="revolute">-->
    <!--<parent link="link2"/>-->
    <!--<child link="link3"/>-->
    <!--<origin xyz="${height2 + axel_offset*2} 0.1 0.1" rpy="0 0 0"/>-->
    <!--<limit effort="100.0" lower="-2.18" upper="2.18" velocity="0.5"/>-->
    <!--<axis xyz="0 0 1"/>-->
    <!--<dynamics damping="0.7"/>-->
  <!--</joint>-->

  <joint name="joint2" type="revolute">
    <parent link="link2"/>
    <child link="coupler2"/>
    <origin xyz="${height2 + axel_offset} 0 0" rpy="0 0 0"/>
    <limit effort="100.0" lower="-2.18" upper="2.18" velocity="0.5"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="coupler2">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${height_axel}" radius="${radius_axel}"/>
      </geometry>
      <material name="white"/>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${height_axel}" radius="${radius_axel}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${dummy_mass}"/>
      <inertia
          ixx="${dummy_inertia}" ixy="0.0" ixz="0.0"
          iyy="${dummy_inertia}" iyz="0.0"
          izz="${dummy_inertia}"/>
    </inertial>
  </link>

  <joint name="coupler_joint2" type="fixed">
    <parent link="coupler2"/>
    <child link="link3"/>
    <origin xyz="${axel_offset} 0 0" rpy="0 0 0"/>
  </joint>

   <!--Top Link-->
  <link name="link3">
    <collision>
      <origin xyz="${height3/2} 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${height3}" radius="${joints_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${height3/2} 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${height3}" radius="${joints_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="${height3/2} 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <mass value="${mass3}"/>
      <inertia
      ixx="${mass3 / 12.0 * (3*joints_radius*joints_radius + height1*height3)}" ixy="0.0" ixz="0.0"
      iyy="${mass3 / 12.0 * (3*joints_radius*joints_radius + height1*height3)}" iyz="0.0"
      izz="${mass3 / 2.0 * (joints_radius*joints_radius)}"/>
    </inertial>
  </link>

  <joint name="gripper_joint" type="fixed">
    <parent link="link3"/>
    <child link="gripper"/>
    <origin xyz="${height3} 0 0" rpy="0 0 0"/>
  </joint>

  <link name="gripper">
    <collision>
      <origin xyz="${z1/2} 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <box size="${yt} ${xt} ${z1}"/>
      </geometry>
      <material name="white"/>
    </collision>
    <collision>
      <origin xyz="${z1+(zt-z1)/2} ${yt/2-y1/2} 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <box size="${y1} ${xt} ${zt-z1}"/>
      </geometry>
      <material name="white"/>
    </collision>
    <collision>
      <origin xyz="${z1+(zt-z1)/2} -${yt/2-y1/2} 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <box size="${y1} ${xt} ${zt-z1}"/>
      </geometry>
      <material name="white"/>
    </collision>

    <visual>
      <origin xyz="${z1/2} 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <box size="${yt} ${xt} ${z1}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <visual>
      <origin xyz="${z1+(zt-z1)/2} ${yt/2-y1/2} 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <box size="${y1} ${xt} ${zt-z1}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <visual>
      <origin xyz="${z1+(zt-z1)/2} -${yt/2-y1/2} 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <box size="${y1} ${xt} ${zt-z1}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${gripper_mass}"/>
      <inertia
          ixx="${dummy_inertia}" ixy="0.0" ixz="0.0"
          iyy="${dummy_inertia}" iyz="0.0"
          izz="${dummy_inertia}"/>
    </inertial>
  </link>

  <joint name="gripper_center_joint" type="fixed">
    <parent link="gripper"/>
    <child link="gripper_center"/>
    <origin xyz="${zt/2+y1/2} 0 0" rpy="0 0 0"/>
  </joint>

  <link name="gripper_center">
    <!--<visual>-->
      <!--<origin xyz="0 0 0" rpy="0 0 0"/>-->
      <!--<geometry>-->
        <!--<cylinder length="${height_axel}" radius="${radius_axel}"/>-->
      <!--</geometry>-->
      <!--<material name="white"/>-->
    <!--</visual>-->
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${dummy_mass}"/>
      <inertia
          ixx="${dummy_inertia}" ixy="0.0" ixz="0.0"
          iyy="${dummy_inertia}" iyz="0.0"
          izz="${dummy_inertia}"/>
    </inertial>
  </link>


  <!--<joint name="hokuyo_joint" type="fixed">-->
    <!--<axis xyz="0 1 0" />-->
    <!--<origin xyz="0 0 ${height3 - axel_offset/2}" rpy="0 0 0"/>-->
    <!--<parent link="link3"/>-->
    <!--<child link="hokuyo_link"/>-->
  <!--</joint>-->

  <!--&lt;!&ndash; Hokuyo Laser &ndash;&gt;-->
  <!--<link name="hokuyo_link">-->
    <!--<collision>-->
      <!--<origin xyz="0 0 0" rpy="0 0 0"/>-->
      <!--<geometry>-->
	<!--<box size="0.1 0.1 0.1"/>-->
      <!--</geometry>-->
    <!--</collision>-->

    <!--<visual>-->
      <!--<origin xyz="0 0 0" rpy="0 0 0"/>-->
      <!--<geometry>-->
        <!--<mesh filename="package://manipulator2d_description/meshes/hokuyo.dae"/>-->
      <!--</geometry>-->
    <!--</visual>-->

    <!--<inertial>-->
      <!--<mass value="1e-5" />-->
      <!--<origin xyz="0 0 0" rpy="0 0 0"/>-->
      <!--<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />-->
    <!--</inertial>-->
  <!--</link>-->

  <!--<joint name="camera_joint" type="fixed">-->
    <!--<axis xyz="0 1 0" />-->
    <!--<origin xyz="${camera_x} ${camera_y} ${camera_z}" rpy="0 ${PI/2} ${PI/2}"/>-->
    <!--<parent link="base_link"/>-->
    <!--<child link="camera_link"/>-->
  <!--</joint>-->

  <!-- Camera -->
  <!--<link name="camera_link">-->
    <!--&lt;!&ndash;<collision>&ndash;&gt;-->
      <!--&lt;!&ndash;<origin xyz="0 0 0" rpy="0 0 0"/>&ndash;&gt;-->
      <!--&lt;!&ndash;<geometry>&ndash;&gt;-->
	<!--&lt;!&ndash;<box size="${camera_link} ${camera_link} ${camera_link}"/>&ndash;&gt;-->
      <!--&lt;!&ndash;</geometry>&ndash;&gt;-->
    <!--&lt;!&ndash;</collision>&ndash;&gt;-->

    <!--&lt;!&ndash;<visual>&ndash;&gt;-->
      <!--&lt;!&ndash;<origin xyz="0 0 0" rpy="0 0 0"/>&ndash;&gt;-->
      <!--&lt;!&ndash;<geometry>&ndash;&gt;-->
	<!--&lt;!&ndash;<box size="${camera_link} ${camera_link} ${camera_link}"/>&ndash;&gt;-->
      <!--&lt;!&ndash;</geometry>&ndash;&gt;-->
      <!--&lt;!&ndash;<material name="red"/>&ndash;&gt;-->
    <!--&lt;!&ndash;</visual>&ndash;&gt;-->

    <!--&lt;!&ndash;<inertial>&ndash;&gt;-->
      <!--&lt;!&ndash;<mass value="1e-5" />&ndash;&gt;-->
      <!--&lt;!&ndash;<origin xyz="0 0 0" rpy="0 0 0"/>&ndash;&gt;-->
      <!--&lt;!&ndash;<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />&ndash;&gt;-->
    <!--&lt;!&ndash;</inertial>&ndash;&gt;-->
  <!--</link>-->

  <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->
  <!--<joint name="camera_optical_joint" type="fixed">-->
    <!--&lt;!&ndash; these values have to be these values otherwise the gazebo camera image-->
        <!--won't be aligned properly with the frame it is supposedly originating from &ndash;&gt;-->
    <!--<origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>-->
    <!--<parent link="camera_link"/>-->
    <!--<child link="camera_link_optical"/>-->
  <!--</joint>-->

  <!--<link name="camera_link_optical">-->
  <!--</link>-->

  <transmission name="tran0">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint0">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor0">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
